[tool.vulture]
ignore_decorators = ["@app.route", "@require_*"]
make_whitelist = true
min_confidence = 80
paths = ["ilobot"]
sort_by_size = true

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = "missing-class-docstring,no-member,missing-function-docstring,missing-module-docstring"

[tool.pytest.ini_options]
log_cli = 1 
asyncio_mode = "auto"