names = {
    "wins": "wins",
    "losses": "losses",
    "otl": "over-time losses",
    "gamesplayed": "games played",
    "goals": "goals",
    "assists": "assists",
    "points": "points",
    "pointspg": "points per game",
    "gwg": "game winning goals",
    "plusmin": "plus minus",
    "toi": "time on ice",
    "pim": "penalty minutes",
    "ppg": "powerplay goals",
    "shg": "shorthanded goals",
    "penaltyshotgoals": "penaltyshot goals",
    "penaltyattempts": "penaltyshot attempts",
    "penaltyshotpct": "penaltyshot percentage",
    "offsides": "offsides",
    "offsidespg": "offsides per game",
    "fights": "fights",
    "fightswon": "fights won",
    "fo": "faceoffs",
    "fow": "faceoffs won",
    "fol": "faceoffs lost",
    "fop": "faceoff percentage",
    "hits": "hits",
    "hitspg": "hits per game",
    "bs": "blocked shots",
    "shots": "shots",
    "shotpct": "shot percentage",
    "shotspg": "shots per game",
    "shotattempts": "shot attempts",
    "shotonnetpct": "shots on net percentage",
    "passes": "passes",
    "passattempts": "pass attempts",
    "passpct": "pass percentage",
    "saucerpasses": "saucer passes",
    "dekes": "dekes",
    "dekesmade": "dekes made",
    "giveaways": "giveaways",
    "takeaways": "takeaways",
    "interceptions": "interceptions",
    "scrnchances": "scoring chances",
    "scrngoals": "screening goals",
    "brkgoals": "breakaway goals",
    "breakaways": "breakaways",
    "breakawaypct": "breakaway percentage",
    "hattricks": "hat tricks",
    "possession": "possession",
    "deflections": "deflections",
    "pkclearzone": "penalty kill clear zone",
    "penaltiesdrawn": "penalties drawn",
    "winpct": "win percentage",
    "record": "record",
    "gamesCompleted": "games completed",
    "winnerByDnf": "winner by dnf",
    "skwins": "skater wins",
    "sklosses": "skater losses",
    "skotl": "skater losses over-time",
    "skwinnerByDnf": "skater wins by dnf",
    "skgoals": "skater goals",
    "skassists": "skater assists",
    "skpoints": "skater points",
    "skpointspg": "skater points per game",
    "skgwg": "skater game winning goals",
    "skplusmin": "skater plus minus",
    "sktoi": "skater time on ice",
    "skpim": "skater penalty minutes",
    "skppg": "skater powerplay goals",
    "skshg": "skater shorthanded goals",
    "skpenaltyshotgoals": "skater penaltyshot goals",
    "skpenaltyattempts": "skater penaltyshot attempts",
    "skpenaltyshotpct": "skater penaltyshot percentage",
    "skoffsides": "skater offsides",
    "skoffsidespg": "skater offsides per game",
    "skfights": "skater fights",
    "skfightswon": "skater fights won",
    "skfo": "skater faceoffs",
    "skfow": "skater faceoff won",
    "skfol": "skater faceoffs lost",
    "skfop": "skater faceoffs percentage",
    "skhits": "skater hits",
    "skhitspg": "skater hits per game",
    "skbs": "skater blocked shots",
    "skshots": "skater shots",
    "skshotpct": "skater shots percentage",
    "skshotspg": "skater shots per game",
    "skshotattempts": "skater shot attempts",
    "skshotonnetpct": "skater shots on net percentage",
    "skpasses": "skater passes",
    "skpassattempts": "skater pass attempts",
    "skpasspct": "skater pass percentage",
    "sksaucerpasses": "skater saucer passes",
    "skdekes": "skater dekes",
    "skdekesmade": "skater dekes made",
    "skgiveaways": "skater giveaways",
    "sktakeaways": "skater takeaways",
    "skinterceptions": "skater interceptions",
    "skscrnchances": "skater scoring chances",
    "skscrngoals": "skater screen goals",
    "skbrkgoals": "skater breakaway goals",
    "skbreakaways": "skater breakaways",
    "skbreakawaypct": "skater breakaway percentage",
    "skgc": "skater gc",
    "skgcFC": "skater gcFC",
    "skhattricks": "skater hattricks",
    "skprevgoals": "skater prevgoals",
    "skprevassists": "skater prevassists",
    "skpossession": "skater possession",
    "skdeflections": "skater deflections",
    "skpkclearzone": "skater clearzone",
    "skpenaltiesdrawn": "skater penalties drawn",
    "skwinpct": "skater win percentage",
    "glwins": "goalie wins",
    "gllosses": "goalie losses",
    "glotl": "goalie losses over-time",
    "glwinnerByDnf": "goalie winnder by dnf",
    "glshots": "goalie shots",
    "glsaves": "goalie saves",
    "glsavepct": "goalie save percentage",
    "gltoi": "goalie time on ice",
    "glga": "goalie goals against",
    "glgaa": "goalie goals against average",
    "glso": "goalie shutouts",
    "glsoperiods": "goalie shutout periods",
    "gldsaves": "goalie dsaves",
    "glbrkshots": "goalie brkshots",
    "glbrksaves": "goalie brksaves",
    "glbrksavepct": "goalie brksaves percentage",
    "glpenshots": "goalie penalty shots",
    "glpensaves": "goalie penalty shot saves",
    "glpensavepct": "goalie penalty shot average",
    "glsoshots": "goalie so shots",
    "glsosaves": "goalie so saves",
    "glsosavepct": "goalie so save percentage",
    "glrecord": "goalie record",
    "glpokechecks": "goalie poke checks",
    "glwinpct": "goalie win percentage",
    "glgc": "goalie gc",
    "glgcFC": "goalie gcFC",
    "glprevwins": "goalie prevwins",
    "glprevso": "goalie prevso",
    "glpkclearzone": "goalie pkclearzone",
    "xfactor_zoneability_goals": "xfactor zoneability goals",
    "xfactor_zoneability_assists": "xfactor zoneability assists",
    "xfactor_zoneability_saves": "xfactor zoneability saves",
    "xfactor_zoneability_hits": "xfactor zoneability hits",
    "xfactor_zoneability_stick_checks": "xfactor zoneability stick checks",
    "xfactor_zoneability_times_used": "xfactor zoneability times used",
    "xfactor_superstarability_goals": "xfactor superstarability goals",
    "xfactor_superstarability_assists": "xfactor superstarability assists",
    "xfactor_superstarability_saves": "xfactor superstarability saves",
    "xfactor_superstarability_hits": "xfactor superstarability hits",
    "xfactor_superstarability_stick_checks": "xfactor superstarability stick checks",
    "glgp": "goalie game played",
    "lwgp": "left wing games played",
    "rwgp": "right wing games played",
    "cgp": "center games played",
    "dgp": "defense games played",
    "skgp": "skater games played",
    "gamesCompletedFC": "games completed FC",
    "lwQuitDisc": "left wing QuitDisc",
    "rwQuitDisc": "right wing QuitDisc",
    "cQuitDisc": "center QuitDisc",
    "dQuitDisc": "defense QuitDisc",
    "glQuitDisc": "goalie QuitDisc",
    "skDNF": "skater DNF",
    "lwDNF": "left wing DNF",
    "rwDNF": "right wing DNF",
    "cDNF": "center DNF",
    "dDNF": "defense DNF",
    "glDNF": "goalie DNF",
    "glDNFmm": "goalie DNF mm",
    "playerQuitDisc": "player QuitDisc",
    "playerDNF": "player DNF",
    "favoritePosition": "favorite position",
    "gp": "gp",
    "DNF": "DNF",
    "prevgoals": "prevgoals",
    "gc": "gc",
    "gcFC": "gcFC",
    "prevassists": "prevassists",
    "name": "name",
}


def get_name(key):
    if key in names:
        return names[key]
    else:
        return key


def get_key(name, data):
    key = ""
    try:
        key = list(data.keys())[list(data.values()).index(name)]
    except ValueError:
        pass
    if key:
        return key
    else:
        return name


match = {
    "points": "points",
    "skassists": "skater assists",
    "skbs": "skater blocked shots",
    "skdeflections": "skater deflections",
    "skfol": "skater faceoffs lost",
    "skfow": "skater faceoff won",
    "skgiveaways": "skater giveaways",
    "skgoals": "skater goals",
    "skhits": "skater hits",
    "skinterceptions": "skater interceptions",
    "skpassattempts": "skater pass attempts",
    "skpasses": "skater passes",
    "skpasspct": "skater pass percentage",
    "skpenaltiesdrawn": "skater penalties drawn",
    "skpim": "skater penalty minutes",
    "skpkclearzone": "skater clearzone",
    "skplusmin": "skater plus minus",
    "skpossession": "skater possession",
    "skppg": "skater powerplay goals",
    "sksaucerpasses": "skater saucer passes",
    "skshg": "skater shorthanded goals",
    "skshotattempts": "skater shot attempts",
    "skshotonnetpct": "skater shots on net percentage",
    "skshotpct": "skater shots percentage",
    "skshots": "skater shots",
    "sktakeaways": "skater takeaways",
    "glbrksavepct": "goalie brksaves percentage",
    "glbrksaves": "goalie brksaves",
    "glbrkshots": "goalie brkshots",
    "glga": "goalie goals against",
    "glgaa": "goalie goals against average",
    "glpensavepct": "goalie penalty shot average",
    "glpensaves": "goalie penalty shot saves",
    "glpenshots": "goalie penalty shots",
    "glpkclearzone": "goalie pkclearzone",
    "glpokechecks": "goalie poke checks",
    "glsavepct": "goalie save percentage",
    "glsaves": "goalie saves",
    "glshots": "goalie shots",
}
